version: "3"

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: ./node-app
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
